### ISSUE TITLE
Does not Ping

### ISSUE THREAD

**Issue by YashKharel19** [Seikho/node-http-ping#2]
Hello, 
I have used the according to same  the documentation but it always shows failure -1 on console my internet is working fine but it is not able to ping.
Thanks!

**Comment by Seikho** [comment]
Hi @YashKharel19 
I've just run the tests and added support for https. Everything still seems to be passing locally for me.
Can you try the examples in the tests?

**Comment by Seikho** [comment]
This library is only supported in Node. It won't work in the browser as the http and https Node APIs aren't available in the browser.

**Comment by YashKharel19** [comment]
@Seikho 
So is their any other way to implement it? Where does it work ?

**Comment by Seikho** [comment]
It'll work on a NodeJS server.
```sh
$ npm install node-http-server
$ + node-http-ping@0.3.1
$ node
> require('node-http-server')('google.com').then(console.log)
> ...
> 289
```

**Comment by YashKharel19** [comment]
$ node
> require('node-http-server')('google.com').then(console.log)
 where do you use this code can you please send me the screenshot.

**Comment by zophiale** [comment]
you can always use webpack to compile, put on a site, and ping it using the file :P but, it is a long and tiring setup... mostly if you do not know how webpack functions
